<template>
  <div>
    <dl>
      <dt>Github</dt>
      <dd>https://www.github.com/renoinn</dd>
    </dl>
    <dl>
      <dt>Twitter</dt>
      <dd>https://www.twitter.com/renoinn</dd>
    </dl>
    <dl>
      <dt>Zenn</dt>
      <dd>https://zenn.dev/renoinn</dd>
    </dl>
  </div>
</template>
